name: Generate PDF render
on: push
jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install -y pandoc texlive-latex-base texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra
      - name: Run Pandoc
        run: pandoc README.md -o constitution.pdf -N -Vmargin-{left,right,top,bottom}:40pt
      - name: Upload Output as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: constitution.pdf
